GymManagementSystem/GymManagementSystem/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

GymManagementSystem/main/urls.py
from xml.dom.minidom import Document
from django import views
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home, name='home'),
    path('pagedetail/<int:id>', views.page_detail, name='pagedetail'),
    path('faq/', views.faq, name='faq'),
    path('enquiry/', views.enquiry, name='enquiry'),
    path('gallery/', views.gallery, name='gallery'),
    path('gallerydetail/<int:id>', views.gallery_detail, name='gallerydetail'),
    path('pricing/', views.pricing, name='pricing'),
    path('accounts/signup', views.signup, name='signup'),
    path('checkout/<int:plan_id>', views.checkout, name='checkout'),
    path('checkout_session/<int:plan_id>', views.checkout_session, name='checkout_session'),
    path('pay_success', views.pay_success, name='pay_success'),
    path('pay_cancel', views.pay_cancel, name='pay_cancel'),
]

# ye samaj nhi aya
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

GymManagementSystem/main/models.py
from distutils.command.upload import upload
from turtle import title
from django.db import models
from django.utils.html import mark_safe
from pygments import highlight
from django.contrib.auth.models import User


# Create your models here.

# banner table to store image and alt_text for image
class Banners(models.Model):
    img = models.ImageField(upload_to='banners/')
    alt_text = models.CharField(max_length=150)

    def __str__(self):
        return self.alt_text

    def image_tag(self):
        return mark_safe('<img src="%s" width="80" />' % (self.img.url))


# service table to store title, detail and image
class Service(models.Model):
    title = models.CharField(max_length=150)
    detail = models.TextField()
    img = models.ImageField(upload_to='service/', null=True)
    
    def __str__(self):
        return self.title

    def image_tag(self):
        return mark_safe('<img src="%s" width="80" />' % (self.img.url))


# pages
class Page(models.Model):
    title = models.CharField(max_length=200)
    detail = models.TextField()

    def __str__(self):
        return self.title

# faq
class Faq(models.Model):
    question = models.TextField()
    ans = models.TextField()

    def __str__(self):
        return self.question

# Enquiry
class Enquiry(models.Model):
    name = models.CharField(max_length=150)
    email = models.EmailField(max_length=150)
    detail = models.TextField()
    send_time = models.DateTimeField(auto_now_add=True)

    # default column in admin page to show object
    def __str__(self):
        return self.name


# Gallery model 
class Gallery(models.Model):
    title = models.CharField(max_length=150)
    detail = models.TextField()
    img = models.ImageField(upload_to="gallery/", null=True)

    def __str__(self) -> str:
        return self.title

    def image_tag(self):
        return mark_safe('<img src="%s" width="80" />' % (self.img.url))

# GalleryImage model 
class GalleryImage(models.Model):
    # foreign key 
    gallery = models.ForeignKey(Gallery, on_delete=models.CASCADE, null=True)
    alt_text = models.CharField(max_length=150)
    img = models.ImageField(upload_to="gallery_img/", null=True)

    def __str__(self) -> str:
        return self.alt_text

    def image_tag(self):
        return mark_safe('<img src="%s" width="80" />' % (self.img.url))


# subscription plan model
class SubPlan(models.Model):
    title = models.CharField(max_length=150)
    price = models.IntegerField()
    max_member=models.IntegerField(null=True)
    highlight_status = models.BooleanField(default=False, null=True)

    def __str__(self):
        return self.title

# subscription features in plan
class SubPlanFeature(models.Model):
    # subplan = models.ForeignKey(SubPlan, on_delete=models.CASCADE, null=True)
    subplan = models.ManyToManyField(SubPlan)
    title = models.CharField(max_length=150)
    
    def __str__(self):
        return self.title

# package discount
class PlanDiscount(models.Model):
    subplan = models.ForeignKey(SubPlan, on_delete=models.CASCADE, null=True)
    total_months = models.IntegerField()
    total_discount = models.IntegerField()
    
    def __str__(self):
        return str(self.total_months)

# subscriber 
class Subscriber(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    mobile = models.CharField(max_length=20)
    address = models.TextField()
    img = models.ImageField(upload_to = "subs/")

    def __str__(self):
        return str(self.user)

    def image_tag(self):
        return mark_safe('<img src="%s" width="80" />' % (self.img.url))

# subscription
class Subscription(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    plan = models.ForeignKey(SubPlan, on_delete=models.CASCADE, null=True)
    price = models.CharField(max_length=50)

GymManagementSystem/main/forms.py
from attr import field
from django import forms
from django.contrib.auth.forms import UserCreationForm 
from django.contrib.auth.models import User
from . import models

# this is model form use to make form from model(database table)
class EnquiryForm(forms.ModelForm):
    class Meta:
        model = models.Enquiry
        fields = ('name', 'email', 'detail')
        
class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name','email','username', 'password1', 'password2']

GymManagementSystem/main/views.py
from contextlib import nullcontext
from gettext import NullTranslations
from turtle import title
from django import forms
from django.shortcuts import render, redirect
from pkg_resources import NullProvider
import service_identity
from . import models
from . import forms
from django.contrib.auth.forms import UserCreationForm
import stripe

# Create your views here.
def home(request):
    banners = models.Banners.objects.all()
    # to fetch only three row
    services = models.Service.objects.all()[:3]
    galleryImages = models.GalleryImage.objects.all().order_by('-id')[:9]
    return render(request, 'home.html', {'banners': banners, 'services':services, 'gallery': galleryImages})


# view with get method
def page_detail(req, id):
    page = models.Page.objects.get(id=id)
    return render(req, 'page.html', {'page':page})

# faq page
def faq(req):
    faq = models.Faq.objects.all()
    return render(req, 'faq.html', {'faqs':faq})

# Enquiry form page
def enquiry(req):
    # handling post method from form 
    msg = ''
    if req.method == 'POST':
        form = forms.EnquiryForm(req.POST)
        if form.is_valid:
            form.save()
            msg = 'data has been saved'

    form = forms.EnquiryForm
    return render(req, 'enquiry.html', {'form':form, 'msg':msg})

# show galleries
def gallery(req):
    gallery = models.Gallery.objects.all().order_by('-id')
    return render(req, 'gallery.html', {'galleries':gallery})

# show galleries detail
def gallery_detail(req, id):
    # fetch title of gallery with their id
    gallery = models.Gallery.objects.get(id=id)
    # get only object containing that gallery in decending order
    galleryImages = models.GalleryImage.objects.filter(gallery=gallery).order_by('-id')
    return render(req, 'gallery_images.html', {'galleryImages':galleryImages, 'gallery':gallery})


# subscription plan
def pricing(req):
    plan = models.SubPlan.objects.all().order_by('price')
    dfeature = models.SubPlanFeature.objects.all()
    return render(req, 'pricing.html', {'plans':plan, 'dfeature':dfeature})

# Signup 
def signup(request):
    msg=None      
    if request.method=='POST':
       form=forms.SignUpForm(request.POST)
       if form.is_valid():
           form.save()
           msg='thank you for register.'

    form=forms.SignUpForm()
    return render(request,'registration/signup.html', {'form':form,'msg':msg})

# Checkout 
def checkout(request,plan_id):
    planDetail = models.SubPlan.objects.get(pk=plan_id)
    return render(request, 'checkout.html', {'plan':planDetail})


stripe.api_key = 'sk_test_51KpDRiSAfp54Ib8XwSTqi5ON9tTBtfCTvZ9ha7W2l8vWmoYbbw1Q7BNdg1K9VHtSONnJL6WRpOZ4L1ZUiXMZgzea00HllVD4F6'

def checkout_session(req, plan_id):
    plan = models.SubPlan.objects.get(pk=plan_id)
    session = stripe.checkout.Session.create(
        payment_method_types=['card'],
        line_items=[{
            'price_data': {
                'currency': 'inr',
                'product_data': {
                'name': plan.title,
                },
                'unit_amount': plan.price*100,
            },
            'quantity': 1,
        }],
        mode='payment',
        success_url='http://localhost:5555/pay_success?session_id={CHECKOUT_SESSION_ID}',
        cancel_url='http://localhost:5555/pay_cancel',
        client_reference_id=plan_id,
    )

    return redirect(session.url, code=303)

# success
def pay_success(req):
    session = stripe.checkout.Session.retrieve(req.GET['session_id'])
    plan_id = session.client_reference_id
    plan = models.SubPlan.objects.get(pk=plan_id)
    user = req.user
    models.Subscription.objects.create(
        plan=plan,
        user=user,
        price=plan.price
    )
    return render(req, 'success.html')

# cancel
def pay_cancel(req):
    return render(req, 'cancel.html')

GymManagementSystem/main/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link href="{% static 'bootstrap.min.css' %}" rel="stylesheet" />
    <!-- Bootstrap Icons -->
    <!-- <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.8.1/bootstrap-icons.svg" /> -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.8.1/font/bootstrap-icons.min.css" integrity="sha512-Oy+sz5W86PK0ZIkawrG0iv7XwWhYecM3exvUtMKNJMekGFJtVAhibhRPTpmyTj8+lJCkmWfnpxKgT2OopquBHA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- jquery -->
    <!-- <script src="assets/jquery-3.6.0.min.js"></script> -->
	<script type="text/javascript" src="{% static 'jquery-3.6.0.min.js' %}"></script>
    <title>Home - ATMA GYM</title>
  </head>
  <body>
    <!-- Header -->
    <nav class="navbar navbar-expand-lg navbar-light bg-warning">
	  <div class="container">
	    <a class="navbar-brand" href="{% url 'home' %}">ATMA GYM</a>
	    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
	      <span class="navbar-toggler-icon"></span>
	    </button>
	    <div class="collapse navbar-collapse" id="navbarNav">
	      <ul class="navbar-nav ms-auto">
	        <li class="nav-item">
	          <a class="nav-link" aria-current="page" href="{% url 'home' %}">Home</a>
	        </li>
	        <li class="nav-item">
	          <a class="nav-link" aria-current="page" href="{% url 'gallery' %}">Gallery</a>
	        </li>
	        <li class="nav-item">
	          <a class="nav-link" href="{% url 'pricing' %}">Pricing</a>
	        </li>
	        <li class="nav-item">
	          <a class="nav-link btn btn-sm btn-dark text-white" href="{% url 'enquiry' %}">Enquiry</a>
	        </li>
	        <li class="nav-item dropdown">
	          <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
	            My Account
	          </a>
	          <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
				{% if not request.user.is_authenticated %}
				<li><a class="dropdown-item" href="{% url 'signup' %}">Register</a></li>
	            <li><a class="dropdown-item" href="{% url 'login' %}">Login</a></li>
				{% else %}
	            <!-- <li><hr class="dropdown-divider"></li> -->
	            <li><a class="dropdown-item" href="#">Profile</a></li>
	            <li><a class="dropdown-item" href="#">Settings</a></li>
	            <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
				{% endif %}
	          </ul>
	        </li>
	      </ul>
	    </div>
	  </div>
	</nav>
    <!-- Header End -->


    {% block content %}

    {% endblock %}

    

    <footer class="container py-5">
	    <p class="float-end"><a href="#">Back to top</a></p>
	    <p>© 2002–2021 ATMA GYM, Inc. · 
            <a href="{% url 'pagedetail' 2 %}">Privacy</a> · 
            <a href="{% url 'pagedetail' 3 %}">Terms</a> · 
            <a href="{% url 'faq' %}">FAQ</a> · 
            <a href="#">Contact Us</a> ·
        </p>
	  </footer>
    <!-- Bootstrap Bundle -->
    <script src="{% static 'bootstrap.bundle.min.js' %}"></script>
  </body>
</html>

GymManagementSystem/main/templates/cancel.html
{% extends 'base.html' %}
{% block content %}
 <!-- Main Start -->
 <main>
    <!-- Services -->
    <section class="container my-4">
        <h3>Sorry please try again</h3>
    </section>
    <!-- End -->
</main>
<!-- End -->

{% endblock content %}

GymManagementSystem/main/templates/checkout.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<main>
  <!-- Services -->
  <section class="container my-4">
    <h1 class="text-center mb-4 section-heading border-bottom pb-2">Checkout</h1>
      <table class="table table-bordered">
        <thead class="table-warning">
          <tr>
            <th>Plan</th>
            <th>Plan Detail</th>
            <th>Payment For</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <table class="table-bordered table">
                <tr>
                  <th>Name</th>
                  <td>{{plan.title}}</td>
                </tr>
                <tr>
                  <th>Price</th>
                  <td>${{plan.price}}</td>
                </tr>
                <tr>
                  <th>Max Member</th>
                  <td>30</td>
                </tr>
                <tr>
                  <th>Already Registered</th>
                  <td>15</td>
                </tr>
                <tr>
                  <th>Balance Seats</th>
                  <td>15</td>
                </tr>
              </table>
            </td>
            <td>
              <ul class="list-unstyled">
                {% for feature in plan.subplanfeature_set.all %}
                 <li>{{ feature.title }}</li>
                {% endfor %}
              </ul>
            </td>
            <td>
              <table class="table table-bordered ">
                {% for discount in plan.plandiscount_set.all %}
                  <tr>
                    <td><input data-planprice="{{plan.price}}" data-discount="{{discount.total_discount}}" type="radio" id="validity{{discount.id}}" name="validity" class="select-validity" value="{{discount.total_months}}"/></td>
                    <th><label for="validity{{discount.id}}">{{discount.total_months}} Month</label></th>
                    <td>{{discount.total_discount}}%</td>
                  </tr> 
                {% endfor %}
              </table>
            </td>
          </tr>
        </tbody>
        <tfoot class="table-info">
          <tr>
            <td></td>
            <th>Total Amount</th>
            <td><b>$<span class="totalAmount">{{ plan.price }}</span></b></td>
          </tr>
          <tr>
              <td colspan="2"></td>
              <td>
              <form action="{% url 'checkout_session' plan.id %}" method="post">
                {% csrf_token %}
                <input type="submit" value="Proceed to Payment" class="btn btn-primary" />
              </form>
              </td>
            
          </tr>
        </tfoot>
      </table>
  </section>
  <!-- End -->
  </main>

<script type="text/javascript">
  $(document).ready(function(){

    $(".select-validity").on('click', function(){
      var _planPrice = $(this).attr('data-planprice');
      var _planValid = $(this).val();
      var _planDisc = $(this).attr('data-discount');
      var _totalPrice = _planPrice * _planValid;

      if(_planDisc > 0){
        var _calDisc = _totalPrice * _planDisc  / 100;
        _calDisc = _totalPrice - _calDisc;
      }else{
        _calDisc = _planPrice;
      }
      
      $('.totalAmount').text(_calDisc);

    })
  });
</script>


{% endblock %}

GymManagementSystem/main/templates/enquiry.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!-- Main Start -->
<main>
    <!-- Services -->
    <section class="container my-4">
        <h1 class="text-center mb-4 section-heading border-bottom pb-2">Enquiry Form</h1>
        <div class="row">
            <div class="col-md-6">
                <img src="{% static 'images/enquiry-1.jpg' %}" class="img-fluid" /> 
            </div>
            <div class="col-md-6">
                {% if msg %}
                <p class="text-success">{{msg}}</p>
                {% endif %}
                <form method="post" action="{% url 'enquiry' %}">
                    {% csrf_token %}
                    <table class="table table-bordered">
                        {{form}}
                        <tr>
                            <td colspan="2">
                                <input type="submit" class="btn btn-primary" />
                            </td>
                        </tr>
                    </table>
                </form>
            </div>
        </div>
    </section>
    <!-- End -->
</main>
<!-- End -->

{% endblock content %}

GymManagementSystem/main/templates/faq.html
{% extends 'base.html' %}
{% block content %}
 <!-- Main Start -->
 <main>
    <!-- Services -->
    <section class="container my-4">
        <h1 class="text-center mb-4 section-heading border-bottom pb-2">FAQ</h1>
        <div class="accordion" id="accordionExample">
          <div class="accordion-item">
                {% for faq in faqs %}
                <h2 class="accordion-header" id="headingOne">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne{{ forloop.counter }}" aria-expanded="true" aria-controls="collapseOne">
                    {{faq.question}}
                </button>
                </h2>
                <div id="collapseOne{{ forloop.counter }}" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
                    <div class="accordion-body">
                        {{faq.ans}}
                    </div>
                </div>
                {% endfor %}
          </div>
          
        </div>
    </section>
    <!-- End -->
</main>
<!-- End -->

{% endblock content %}

GymManagementSystem/main/templates/gallery.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!-- Main Start -->
<main>
    <!-- Services -->
    <section class="container my-4">
        <h1 class="text-center mb-4 section-heading border-bottom pb-2">Gallery</h1>
        <div class="row">
          {% for gallery in galleries %}
            <div class="col-md-4 mb-4">
                <div class="card">
                  <img src="{{gallery.img.url}}" class="card-img-top" alt="...">
                  <div class="card-body">
                    <h5 class="card-title">{{gallery.title}}</h5>
                    <p class="card-text">{{gallery.detail}}</p>
                    <a href="{% url 'gallerydetail' gallery.id %}" class="btn btn-primary">View All</a>
                  </div>
                </div>
            </div>
          {% endfor %}
        </div>
    </section>
    <!-- End -->
</main>
<!-- End -->

{% endblock content %}

GymManagementSystem/main/templates/gallery_images.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!-- Main Start -->
<main>
    <!-- Services -->
    <section class="container my-4">
        <h1 class="text-center mb-4 section-heading border-bottom pb-2">{{gallery.title}} Images</h1>
        <div class="row">
          {% for galleryImage in galleryImages %}
            <div class="col-md-4 mb-4">
                <div class="card">
                  <img src="{{galleryImage.img.url}}" class="card-img-top" alt="galleryImage.alt_text">
                  <!-- <div class="card-body">
                    <h5 class="card-title">{{gallery.title}}</h5>
                    <p class="card-text">{{gallery.detail}}</p>
                    <a href="#" class="btn btn-primary">View All</a>
                  </div> -->
                </div>
            </div>
          {% endfor %}
        </div>
    </section>
    <!-- End -->
</main>
<!-- End -->

{% endblock content %}

GymManagementSystem/main/templates/home.html
 {% extends 'base.html' %}
{% load static %}
{% block content %}
    <!-- Main Start -->
    <main>
    	<!-- banner Start -->
    	<div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
		  <div class="carousel-inner">
			{% for banner in banners %}
		    <div class="carousel-item {% if forloop.counter == 1 %} active {% endif %}">
		      <img src="{{banner.img.url}}" class="d-block w-100" alt="Slide 1">
		    </div>
			{% endfor %}
		  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
		    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
		    <span class="visually-hidden">Previous</span>
		  </button>
		  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
		    <span class="carousel-control-next-icon" aria-hidden="true"></span>
		    <span class="visually-hidden">Next</span>
		  </button>
		</div>
		<!-- End Banner -->

		<!-- Services -->
		<section class="container my-4">
			<h1 class="text-center mb-4 section-heading">Services</h1>
			<div class="row">
				{% for service in services %}
				<div class="col-md-4">
					<div class="card">
					  <img src="{{ service.img.url }}" class="card-img-top" alt="...">
					  <div class="card-body">
					    <h3 class="card-title">{{ service.title }}</h3>
					    <p class="card-text">{{service.detail}}</p>
					    <a href="service.php" class="btn btn-primary">Read More</a>
					  </div>
					</div>
				</div>
				{% endfor %}
			</div>
		</section>
		<!-- End Sevices -->

		<!-- Testimonials -->
		<section class="container-fluid bg-light py-4 mt-5 border-top border-bottom">
			<div class="container">
				<div class="row">
					<div class="col-md-5">
							<h1 class="mb-4 section-heading">About Us</h1>
							<p class="lh-base">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1550s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
							<p><a href="{% url 'pagedetail' 1 %}" class="btn btn-info text-white">Read More</a></p>
					</div>
					<div class="col-md-6 offset-1">
							<h1 class="mb-4 section-heading">Gallery <a href="#" class="float-end btn btn-info text-white mt-2">View All</a></h1>
							<div class="gallery">
								{% for gimg in gallery %}
								<a data-lightbox="roadtrip" href="{{ gimg.img.url }}"><img src="{{ gimg.img.url }}" width="155" class="img-thumbnail" alt="{{ gimg.img.alt_text }}"></a>
								{% endfor %}
							</div>
					</div>
				</div>
			</div>
		</section>
		<!-- End Testimonials -->

    </main>
    <!-- End -->

	<!-- lightbox css -->
	<link rel="stylesheet" href="{% static 'lightbox2-dev/dist/css/lightbox.min.css' %}">
	<!-- lightbox js -->
	<script src="{% static 'lightbox2-dev/dist/js/lightbox.min.js' %}"></script>

    {% endblock %}

GymManagementSystem/main/templates/page.html
{% extends 'base.html' %}
{% block content %}
    <!-- Main Start -->
    <main>
		<!-- pages -->
		<section class="container my-4">
			<h1 class="text-center mb-4 section-heading border-bottom pb-2">{{page.title}}</h1>
			<p>{{page.detail}}</p>
		</section>
		<!-- End -->
    </main>
    <!-- End -->

    {% endblock %}

GymManagementSystem/main/templates/pricing.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


<!-- Main Start -->
<section class="container my-4">
    <h1 class="text-center mb-4 section-heading border-bottom pb-2">Plans</h1>
<main>
<div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
    {% for plan in plans %}
    
  <div class="col">
    <div class="card mb-4 rounded-3 shadow-sm {% if plan.highlight_status %} border-primary {% endif %}">
        {% if plan.highlight_status %}
            <div class="card-header py-3 text-white bg-primary border-primary">
        {% else %}
            <div class="card-header py-3">
        {% endif %}
        <h4 class="my-0 fw-normal">{{ plan.title }}</h4>
      </div>
      <div class="card-body">
        <h1 class="card-title pricing-card-title">₹{{ plan.price }}<small class="text-muted fw-light">/mo</small>
        </h1>
          <p class="text-success"> Members Capacity {{plan.max_member}}</p>
        
        <ul class="list-unstyled mt-3 mb-4">
            <!-- nhi samja -->
          {% for feature in plan.subplanfeature_set.all %}
            <li>{{ feature.title }}</li>
          {% endfor %}
          <!-- <li>Diet Plan</li>
          <li>...</li>
          <li>...</li> -->
        </ul>
        {% if request.user.is_authenticated %}
        <a href="{% url 'checkout' plan.id %}" class="w-100 btn btn-lg btn-outline-primary">Get started</a>
        {% else %}
        <a href="{% url 'login' %} " class="w-100 btn btn-lg btn-outline-primary">Get started</a>
        {% endif %}
      </div>
    </div>
  </div>
  {% endfor %}

</div>

<h2 class="display-6 text-center mb-4">Compare plans</h2>

<div class="table-responsive">
  <table class="table text-center">
    <thead>
      <tr>
        <th style="width: 34%;"></th>
        {% for plan in plans %}
            <th style="width: 22%;">{{ plan.title }}</th>
        {% endfor %}
        <!-- <th style="width: 22%;">Medium</th>
        <th style="width: 22%;">Advance</th> -->
      </tr>
    </thead>
    <tbody>
      <!-- nhi samja kuch  -->
        {% for feature in dfeature %}
      <tr>
        <th scope="row" class="text-start">{{feature.title }}</th>
        {% for plan in plans %}
        <td>
            {% if plan in feature.subplan.all %}
                <i class="bi bi-check-lg text-success"></i>
            {% else %}
                <i class="bi bi-x-lg text-danger"></i>
            {% endif %}
        </td>
        {% endfor %}

        <!-- <td><i class="bi bi-check-lg"></i></td>
        <td><i class="bi bi-check-lg"></i></td> -->
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
</main>
</section>
<!-- End -->

{% endblock content %}

GymManagementSystem/main/templates/success.html
{% extends 'base.html' %}
{% block content %}
 <!-- Main Start -->
 <main>
    <!-- Services -->
    <section class="container my-4">
        <h3>Thanks for payment</h3>
    </section>
    <!-- End -->
</main>
<!-- End -->

{% endblock content %}